// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
import f0 from '@fontsource/inter/files/inter-latin-400-normal.woff2?url';
import f1 from '@fontsource/inter/files/inter-latin-ext-400-normal.woff2?url';
import f2 from '@fontsource/inter/files/inter-latin-400-italic.woff2?url';
import f3 from '@fontsource/inter/files/inter-latin-ext-400-italic.woff2?url';
import f4 from '@fontsource/inter/files/inter-latin-500-normal.woff2?url';
import f5 from '@fontsource/inter/files/inter-latin-ext-500-normal.woff2?url';
import f6 from '@fontsource/inter/files/inter-latin-500-italic.woff2?url';
import f7 from '@fontsource/inter/files/inter-latin-ext-500-italic.woff2?url';
import f8 from '@fontsource/inter/files/inter-latin-700-normal.woff2?url';
import f9 from '@fontsource/inter/files/inter-latin-ext-700-normal.woff2?url';
import f10 from '@fontsource/inter/files/inter-latin-700-italic.woff2?url';
import f11 from '@fontsource/inter/files/inter-latin-ext-700-italic.woff2?url';
import f12 from '@fontsource/inter/files/inter-latin-800-normal.woff2?url';
import f13 from '@fontsource/inter/files/inter-latin-ext-800-normal.woff2?url';
import f14 from '@fontsource/inter/files/inter-latin-800-italic.woff2?url';
import f15 from '@fontsource/inter/files/inter-latin-ext-800-italic.woff2?url';
import f16 from '@fontsource/inter/files/inter-latin-900-normal.woff2?url';
import f17 from '@fontsource/inter/files/inter-latin-ext-900-normal.woff2?url';
import f18 from '@fontsource/inter/files/inter-latin-900-italic.woff2?url';
import f19 from '@fontsource/inter/files/inter-latin-ext-900-italic.woff2?url';
import f20 from '@fontsource/roboto/files/roboto-latin-400-normal.woff2?url';
import f21 from '@fontsource/roboto/files/roboto-latin-ext-400-normal.woff2?url';
import f22 from '@fontsource/roboto/files/roboto-latin-400-italic.woff2?url';
import f23 from '@fontsource/roboto/files/roboto-latin-ext-400-italic.woff2?url';
import f24 from '@fontsource/roboto/files/roboto-latin-700-normal.woff2?url';
import f25 from '@fontsource/roboto/files/roboto-latin-ext-700-normal.woff2?url';
import f26 from '@fontsource/roboto/files/roboto-latin-700-italic.woff2?url';
import f27 from '@fontsource/roboto/files/roboto-latin-ext-700-italic.woff2?url';
import f28 from '@fontsource/roboto/files/roboto-latin-900-normal.woff2?url';
import f29 from '@fontsource/roboto/files/roboto-latin-ext-900-normal.woff2?url';
import f30 from '@fontsource/roboto/files/roboto-latin-900-italic.woff2?url';
import f31 from '@fontsource/roboto/files/roboto-latin-ext-900-italic.woff2?url';
import f32 from '@fontsource/montserrat/files/montserrat-latin-400-normal.woff2?url';
import f33 from '@fontsource/montserrat/files/montserrat-latin-ext-400-normal.woff2?url';
import f34 from '@fontsource/montserrat/files/montserrat-latin-400-italic.woff2?url';
import f35 from '@fontsource/montserrat/files/montserrat-latin-ext-400-italic.woff2?url';
import f36 from '@fontsource/montserrat/files/montserrat-latin-600-normal.woff2?url';
import f37 from '@fontsource/montserrat/files/montserrat-latin-ext-600-normal.woff2?url';
import f38 from '@fontsource/montserrat/files/montserrat-latin-600-italic.woff2?url';
import f39 from '@fontsource/montserrat/files/montserrat-latin-ext-600-italic.woff2?url';
import f40 from '@fontsource/montserrat/files/montserrat-latin-800-normal.woff2?url';
import f41 from '@fontsource/montserrat/files/montserrat-latin-ext-800-normal.woff2?url';
import f42 from '@fontsource/montserrat/files/montserrat-latin-800-italic.woff2?url';
import f43 from '@fontsource/montserrat/files/montserrat-latin-ext-800-italic.woff2?url';
import f44 from '@fontsource/montserrat/files/montserrat-latin-900-normal.woff2?url';
import f45 from '@fontsource/montserrat/files/montserrat-latin-ext-900-normal.woff2?url';
import f46 from '@fontsource/montserrat/files/montserrat-latin-900-italic.woff2?url';
import f47 from '@fontsource/montserrat/files/montserrat-latin-ext-900-italic.woff2?url';
import f48 from '@fontsource/poppins/files/poppins-latin-400-normal.woff2?url';
import f49 from '@fontsource/poppins/files/poppins-latin-ext-400-normal.woff2?url';
import f50 from '@fontsource/poppins/files/poppins-latin-400-italic.woff2?url';
import f51 from '@fontsource/poppins/files/poppins-latin-ext-400-italic.woff2?url';
import f52 from '@fontsource/poppins/files/poppins-latin-600-normal.woff2?url';
import f53 from '@fontsource/poppins/files/poppins-latin-ext-600-normal.woff2?url';
import f54 from '@fontsource/poppins/files/poppins-latin-600-italic.woff2?url';
import f55 from '@fontsource/poppins/files/poppins-latin-ext-600-italic.woff2?url';
import f56 from '@fontsource/poppins/files/poppins-latin-800-normal.woff2?url';
import f57 from '@fontsource/poppins/files/poppins-latin-ext-800-normal.woff2?url';
import f58 from '@fontsource/poppins/files/poppins-latin-800-italic.woff2?url';
import f59 from '@fontsource/poppins/files/poppins-latin-ext-800-italic.woff2?url';
import f60 from '@fontsource/oswald/files/oswald-latin-400-normal.woff2?url';
import f61 from '@fontsource/oswald/files/oswald-latin-ext-400-normal.woff2?url';
import f62 from '@fontsource/oswald/files/oswald-latin-600-normal.woff2?url';
import f63 from '@fontsource/oswald/files/oswald-latin-ext-600-normal.woff2?url';
import f64 from '@fontsource/bebas-neue/files/bebas-neue-latin-400-normal.woff2?url';
import f65 from '@fontsource/bebas-neue/files/bebas-neue-latin-ext-400-normal.woff2?url';
import f66 from '@fontsource/anton/files/anton-latin-400-normal.woff2?url';
import f67 from '@fontsource/anton/files/anton-latin-ext-400-normal.woff2?url';
import f68 from '@fontsource/playfair-display/files/playfair-display-latin-400-normal.woff2?url';
import f69 from '@fontsource/playfair-display/files/playfair-display-latin-ext-400-normal.woff2?url';
import f70 from '@fontsource/playfair-display/files/playfair-display-latin-400-italic.woff2?url';
import f71 from '@fontsource/playfair-display/files/playfair-display-latin-ext-400-italic.woff2?url';
import f72 from '@fontsource/playfair-display/files/playfair-display-latin-700-normal.woff2?url';
import f73 from '@fontsource/playfair-display/files/playfair-display-latin-ext-700-normal.woff2?url';
import f74 from '@fontsource/playfair-display/files/playfair-display-latin-700-italic.woff2?url';
import f75 from '@fontsource/playfair-display/files/playfair-display-latin-ext-700-italic.woff2?url';
import f76 from '@fontsource/playfair-display/files/playfair-display-latin-900-normal.woff2?url';
import f77 from '@fontsource/playfair-display/files/playfair-display-latin-ext-900-normal.woff2?url';
import f78 from '@fontsource/playfair-display/files/playfair-display-latin-900-italic.woff2?url';
import f79 from '@fontsource/playfair-display/files/playfair-display-latin-ext-900-italic.woff2?url';
import f80 from '@fontsource/merriweather/files/merriweather-latin-400-normal.woff2?url';
import f81 from '@fontsource/merriweather/files/merriweather-latin-ext-400-normal.woff2?url';
import f82 from '@fontsource/merriweather/files/merriweather-latin-400-italic.woff2?url';
import f83 from '@fontsource/merriweather/files/merriweather-latin-ext-400-italic.woff2?url';
import f84 from '@fontsource/merriweather/files/merriweather-latin-700-normal.woff2?url';
import f85 from '@fontsource/merriweather/files/merriweather-latin-ext-700-normal.woff2?url';
import f86 from '@fontsource/merriweather/files/merriweather-latin-700-italic.woff2?url';
import f87 from '@fontsource/merriweather/files/merriweather-latin-ext-700-italic.woff2?url';
import f88 from '@fontsource/lora/files/lora-latin-400-normal.woff2?url';
import f89 from '@fontsource/lora/files/lora-latin-ext-400-normal.woff2?url';
import f90 from '@fontsource/lora/files/lora-latin-400-italic.woff2?url';
import f91 from '@fontsource/lora/files/lora-latin-ext-400-italic.woff2?url';
import f92 from '@fontsource/lora/files/lora-latin-700-normal.woff2?url';
import f93 from '@fontsource/lora/files/lora-latin-ext-700-normal.woff2?url';
import f94 from '@fontsource/lora/files/lora-latin-700-italic.woff2?url';
import f95 from '@fontsource/lora/files/lora-latin-ext-700-italic.woff2?url';
import f96 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff2?url';
import f97 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-ext-400-normal.woff2?url';
import f98 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-400-italic.woff2?url';
import f99 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-ext-400-italic.woff2?url';
import f100 from '@fontsource/dancing-script/files/dancing-script-latin-400-normal.woff2?url';
import f101 from '@fontsource/dancing-script/files/dancing-script-latin-ext-400-normal.woff2?url';
import f102 from '@fontsource/dancing-script/files/dancing-script-latin-700-normal.woff2?url';
import f103 from '@fontsource/dancing-script/files/dancing-script-latin-ext-700-normal.woff2?url';
import f104 from '@fontsource/pacifico/files/pacifico-latin-400-normal.woff2?url';
import f105 from '@fontsource/pacifico/files/pacifico-latin-ext-400-normal.woff2?url';
import f106 from '@fontsource/lobster/files/lobster-latin-400-normal.woff2?url';
import f107 from '@fontsource/lobster/files/lobster-latin-ext-400-normal.woff2?url';
import f108 from '@fontsource/caveat/files/caveat-latin-400-normal.woff2?url';
import f109 from '@fontsource/caveat/files/caveat-latin-ext-400-normal.woff2?url';
import f110 from '@fontsource/caveat/files/caveat-latin-700-normal.woff2?url';
import f111 from '@fontsource/caveat/files/caveat-latin-ext-700-normal.woff2?url';
import f112 from '@fontsource/permanent-marker/files/permanent-marker-latin-400-normal.woff2?url';
import f113 from '@fontsource/bangers/files/bangers-latin-400-normal.woff2?url';
import f114 from '@fontsource/bangers/files/bangers-latin-ext-400-normal.woff2?url';
import f115 from '@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff2?url';
import f116 from '@fontsource/archivo-black/files/archivo-black-latin-ext-400-normal.woff2?url';
import f117 from '@fontsource/righteous/files/righteous-latin-400-normal.woff2?url';
import f118 from '@fontsource/righteous/files/righteous-latin-ext-400-normal.woff2?url';
import f119 from '@fontsource/space-grotesk/files/space-grotesk-latin-400-normal.woff2?url';
import f120 from '@fontsource/space-grotesk/files/space-grotesk-latin-ext-400-normal.woff2?url';
import f121 from '@fontsource/space-grotesk/files/space-grotesk-latin-700-normal.woff2?url';
import f122 from '@fontsource/space-grotesk/files/space-grotesk-latin-ext-700-normal.woff2?url';
import f123 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-400-normal.woff2?url';
import f124 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-ext-400-normal.woff2?url';
import f125 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-400-italic.woff2?url';
import f126 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-ext-400-italic.woff2?url';
import f127 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-700-normal.woff2?url';
import f128 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-ext-700-normal.woff2?url';
import f129 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-700-italic.woff2?url';
import f130 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-ext-700-italic.woff2?url';
import f131 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-900-normal.woff2?url';
import f132 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-ext-900-normal.woff2?url';
import f133 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-900-italic.woff2?url';
import f134 from '@fontsource/barlow-condensed/files/barlow-condensed-latin-ext-900-italic.woff2?url';
import f135 from '@fontsource/nunito/files/nunito-latin-400-normal.woff2?url';
import f136 from '@fontsource/nunito/files/nunito-latin-ext-400-normal.woff2?url';
import f137 from '@fontsource/nunito/files/nunito-latin-400-italic.woff2?url';
import f138 from '@fontsource/nunito/files/nunito-latin-ext-400-italic.woff2?url';
import f139 from '@fontsource/nunito/files/nunito-latin-800-normal.woff2?url';
import f140 from '@fontsource/nunito/files/nunito-latin-ext-800-normal.woff2?url';
import f141 from '@fontsource/nunito/files/nunito-latin-800-italic.woff2?url';
import f142 from '@fontsource/nunito/files/nunito-latin-ext-800-italic.woff2?url';
import f143 from '@fontsource/rubik/files/rubik-latin-400-normal.woff2?url';
import f144 from '@fontsource/rubik/files/rubik-latin-ext-400-normal.woff2?url';
import f145 from '@fontsource/rubik/files/rubik-latin-400-italic.woff2?url';
import f146 from '@fontsource/rubik/files/rubik-latin-ext-400-italic.woff2?url';
import f147 from '@fontsource/rubik/files/rubik-latin-700-normal.woff2?url';
import f148 from '@fontsource/rubik/files/rubik-latin-ext-700-normal.woff2?url';
import f149 from '@fontsource/rubik/files/rubik-latin-700-italic.woff2?url';
import f150 from '@fontsource/rubik/files/rubik-latin-ext-700-italic.woff2?url';
import f151 from '@fontsource/roboto-mono/files/roboto-mono-latin-400-normal.woff2?url';
import f152 from '@fontsource/roboto-mono/files/roboto-mono-latin-ext-400-normal.woff2?url';
import f153 from '@fontsource/roboto-mono/files/roboto-mono-latin-400-italic.woff2?url';
import f154 from '@fontsource/roboto-mono/files/roboto-mono-latin-ext-400-italic.woff2?url';
import f155 from '@fontsource/roboto-mono/files/roboto-mono-latin-700-normal.woff2?url';
import f156 from '@fontsource/roboto-mono/files/roboto-mono-latin-ext-700-normal.woff2?url';
import f157 from '@fontsource/roboto-mono/files/roboto-mono-latin-700-italic.woff2?url';
import f158 from '@fontsource/roboto-mono/files/roboto-mono-latin-ext-700-italic.woff2?url';

export interface FontFaceEntry { url: string; weight: number; italic: boolean; unicodeRange?: string }
export interface FontFamilyEntry { family: string; category: 'sans' | 'serif' | 'script' | 'display' | 'mono'; faces: FontFaceEntry[] }

export const BUNDLED_FONTS: FontFamilyEntry[] = [
  { family: "Inter", category: "sans", faces: [
    { url: f0, weight: 400, italic: false },
    { url: f1, weight: 400, italic: false },
    { url: f2, weight: 400, italic: true },
    { url: f3, weight: 400, italic: true },
    { url: f4, weight: 500, italic: false },
    { url: f5, weight: 500, italic: false },
    { url: f6, weight: 500, italic: true },
    { url: f7, weight: 500, italic: true },
    { url: f8, weight: 700, italic: false },
    { url: f9, weight: 700, italic: false },
    { url: f10, weight: 700, italic: true },
    { url: f11, weight: 700, italic: true },
    { url: f12, weight: 800, italic: false },
    { url: f13, weight: 800, italic: false },
    { url: f14, weight: 800, italic: true },
    { url: f15, weight: 800, italic: true },
    { url: f16, weight: 900, italic: false },
    { url: f17, weight: 900, italic: false },
    { url: f18, weight: 900, italic: true },
    { url: f19, weight: 900, italic: true },
  ] },
  { family: "Roboto", category: "sans", faces: [
    { url: f20, weight: 400, italic: false },
    { url: f21, weight: 400, italic: false },
    { url: f22, weight: 400, italic: true },
    { url: f23, weight: 400, italic: true },
    { url: f24, weight: 700, italic: false },
    { url: f25, weight: 700, italic: false },
    { url: f26, weight: 700, italic: true },
    { url: f27, weight: 700, italic: true },
    { url: f28, weight: 900, italic: false },
    { url: f29, weight: 900, italic: false },
    { url: f30, weight: 900, italic: true },
    { url: f31, weight: 900, italic: true },
  ] },
  { family: "Montserrat", category: "sans", faces: [
    { url: f32, weight: 400, italic: false },
    { url: f33, weight: 400, italic: false },
    { url: f34, weight: 400, italic: true },
    { url: f35, weight: 400, italic: true },
    { url: f36, weight: 600, italic: false },
    { url: f37, weight: 600, italic: false },
    { url: f38, weight: 600, italic: true },
    { url: f39, weight: 600, italic: true },
    { url: f40, weight: 800, italic: false },
    { url: f41, weight: 800, italic: false },
    { url: f42, weight: 800, italic: true },
    { url: f43, weight: 800, italic: true },
    { url: f44, weight: 900, italic: false },
    { url: f45, weight: 900, italic: false },
    { url: f46, weight: 900, italic: true },
    { url: f47, weight: 900, italic: true },
  ] },
  { family: "Poppins", category: "sans", faces: [
    { url: f48, weight: 400, italic: false },
    { url: f49, weight: 400, italic: false },
    { url: f50, weight: 400, italic: true },
    { url: f51, weight: 400, italic: true },
    { url: f52, weight: 600, italic: false },
    { url: f53, weight: 600, italic: false },
    { url: f54, weight: 600, italic: true },
    { url: f55, weight: 600, italic: true },
    { url: f56, weight: 800, italic: false },
    { url: f57, weight: 800, italic: false },
    { url: f58, weight: 800, italic: true },
    { url: f59, weight: 800, italic: true },
  ] },
  { family: "Oswald", category: "display", faces: [
    { url: f60, weight: 400, italic: false },
    { url: f61, weight: 400, italic: false },
    { url: f62, weight: 600, italic: false },
    { url: f63, weight: 600, italic: false },
  ] },
  { family: "Bebas Neue", category: "display", faces: [
    { url: f64, weight: 400, italic: false },
    { url: f65, weight: 400, italic: false },
  ] },
  { family: "Anton", category: "display", faces: [
    { url: f66, weight: 400, italic: false },
    { url: f67, weight: 400, italic: false },
  ] },
  { family: "Playfair Display", category: "serif", faces: [
    { url: f68, weight: 400, italic: false },
    { url: f69, weight: 400, italic: false },
    { url: f70, weight: 400, italic: true },
    { url: f71, weight: 400, italic: true },
    { url: f72, weight: 700, italic: false },
    { url: f73, weight: 700, italic: false },
    { url: f74, weight: 700, italic: true },
    { url: f75, weight: 700, italic: true },
    { url: f76, weight: 900, italic: false },
    { url: f77, weight: 900, italic: false },
    { url: f78, weight: 900, italic: true },
    { url: f79, weight: 900, italic: true },
  ] },
  { family: "Merriweather", category: "serif", faces: [
    { url: f80, weight: 400, italic: false },
    { url: f81, weight: 400, italic: false },
    { url: f82, weight: 400, italic: true },
    { url: f83, weight: 400, italic: true },
    { url: f84, weight: 700, italic: false },
    { url: f85, weight: 700, italic: false },
    { url: f86, weight: 700, italic: true },
    { url: f87, weight: 700, italic: true },
  ] },
  { family: "Lora", category: "serif", faces: [
    { url: f88, weight: 400, italic: false },
    { url: f89, weight: 400, italic: false },
    { url: f90, weight: 400, italic: true },
    { url: f91, weight: 400, italic: true },
    { url: f92, weight: 700, italic: false },
    { url: f93, weight: 700, italic: false },
    { url: f94, weight: 700, italic: true },
    { url: f95, weight: 700, italic: true },
  ] },
  { family: "DM Serif Display", category: "serif", faces: [
    { url: f96, weight: 400, italic: false },
    { url: f97, weight: 400, italic: false },
    { url: f98, weight: 400, italic: true },
    { url: f99, weight: 400, italic: true },
  ] },
  { family: "Dancing Script", category: "script", faces: [
    { url: f100, weight: 400, italic: false },
    { url: f101, weight: 400, italic: false },
    { url: f102, weight: 700, italic: false },
    { url: f103, weight: 700, italic: false },
  ] },
  { family: "Pacifico", category: "script", faces: [
    { url: f104, weight: 400, italic: false },
    { url: f105, weight: 400, italic: false },
  ] },
  { family: "Lobster", category: "script", faces: [
    { url: f106, weight: 400, italic: false },
    { url: f107, weight: 400, italic: false },
  ] },
  { family: "Caveat", category: "script", faces: [
    { url: f108, weight: 400, italic: false },
    { url: f109, weight: 400, italic: false },
    { url: f110, weight: 700, italic: false },
    { url: f111, weight: 700, italic: false },
  ] },
  { family: "Permanent Marker", category: "script", faces: [
    { url: f112, weight: 400, italic: false },
  ] },
  { family: "Bangers", category: "display", faces: [
    { url: f113, weight: 400, italic: false },
    { url: f114, weight: 400, italic: false },
  ] },
  { family: "Archivo Black", category: "display", faces: [
    { url: f115, weight: 400, italic: false },
    { url: f116, weight: 400, italic: false },
  ] },
  { family: "Righteous", category: "display", faces: [
    { url: f117, weight: 400, italic: false },
    { url: f118, weight: 400, italic: false },
  ] },
  { family: "Space Grotesk", category: "sans", faces: [
    { url: f119, weight: 400, italic: false },
    { url: f120, weight: 400, italic: false },
    { url: f121, weight: 700, italic: false },
    { url: f122, weight: 700, italic: false },
  ] },
  { family: "Barlow Condensed", category: "display", faces: [
    { url: f123, weight: 400, italic: false },
    { url: f124, weight: 400, italic: false },
    { url: f125, weight: 400, italic: true },
    { url: f126, weight: 400, italic: true },
    { url: f127, weight: 700, italic: false },
    { url: f128, weight: 700, italic: false },
    { url: f129, weight: 700, italic: true },
    { url: f130, weight: 700, italic: true },
    { url: f131, weight: 900, italic: false },
    { url: f132, weight: 900, italic: false },
    { url: f133, weight: 900, italic: true },
    { url: f134, weight: 900, italic: true },
  ] },
  { family: "Nunito", category: "sans", faces: [
    { url: f135, weight: 400, italic: false },
    { url: f136, weight: 400, italic: false },
    { url: f137, weight: 400, italic: true },
    { url: f138, weight: 400, italic: true },
    { url: f139, weight: 800, italic: false },
    { url: f140, weight: 800, italic: false },
    { url: f141, weight: 800, italic: true },
    { url: f142, weight: 800, italic: true },
  ] },
  { family: "Rubik", category: "sans", faces: [
    { url: f143, weight: 400, italic: false },
    { url: f144, weight: 400, italic: false },
    { url: f145, weight: 400, italic: true },
    { url: f146, weight: 400, italic: true },
    { url: f147, weight: 700, italic: false },
    { url: f148, weight: 700, italic: false },
    { url: f149, weight: 700, italic: true },
    { url: f150, weight: 700, italic: true },
  ] },
  { family: "Roboto Mono", category: "mono", faces: [
    { url: f151, weight: 400, italic: false },
    { url: f152, weight: 400, italic: false },
    { url: f153, weight: 400, italic: true },
    { url: f154, weight: 400, italic: true },
    { url: f155, weight: 700, italic: false },
    { url: f156, weight: 700, italic: false },
    { url: f157, weight: 700, italic: true },
    { url: f158, weight: 700, italic: true },
  ] },
];
