// Generates src/engine/fontManifest.ts from installed @fontsource packages.
// Run: node scripts/gen-fonts.mjs
import fs from 'node:fs';
import path from 'node:path';

const FAMILIES = {
  'Inter': ['inter', ['400', '500', '700', '800', '900', '400i', '700i']],
  'Roboto': ['roboto', ['400', '700', '900', '400i']],
  'Montserrat': ['montserrat', ['400', '600', '800', '900']],
  'Poppins': ['poppins', ['400', '600', '800']],
  'Oswald': ['oswald', ['400', '600']],
  'Bebas Neue': ['bebas-neue', ['400']],
  'Anton': ['anton', ['400']],
  'Playfair Display': ['playfair-display', ['400', '700', '900', '400i']],
  'Merriweather': ['merriweather', ['400', '700']],
  'Lora': ['lora', ['400', '700', '400i']],
  'DM Serif Display': ['dm-serif-display', ['400', '400i']],
  'Dancing Script': ['dancing-script', ['400', '700']],
  'Pacifico': ['pacifico', ['400']],
  'Lobster': ['lobster', ['400']],
  'Caveat': ['caveat', ['400', '700']],
  'Permanent Marker': ['permanent-marker', ['400']],
  'Bangers': ['bangers', ['400']],
  'Archivo Black': ['archivo-black', ['400']],
  'Righteous': ['righteous', ['400']],
  'Space Grotesk': ['space-grotesk', ['400', '700']],
  'Barlow Condensed': ['barlow-condensed', ['400', '700', '900']],
  'Nunito': ['nunito', ['400', '800']],
  'Rubik': ['rubik', ['400', '700']],
  'Roboto Mono': ['roboto-mono', ['400', '700']],
};
const CATEGORY = {
  'Playfair Display': 'serif', 'Merriweather': 'serif', 'Lora': 'serif', 'DM Serif Display': 'serif',
  'Dancing Script': 'script', 'Pacifico': 'script', 'Lobster': 'script', 'Caveat': 'script', 'Permanent Marker': 'script',
  'Bangers': 'display', 'Bebas Neue': 'display', 'Anton': 'display', 'Archivo Black': 'display', 'Righteous': 'display', 'Oswald': 'display', 'Barlow Condensed': 'display',
  'Roboto Mono': 'mono',
};

const root = 'node_modules/@fontsource';
function unicodeRange(pkg, subset) {
  const css = path.join(root, pkg, `${subset}.css`);
  if (!fs.existsSync(css)) return null;
  const m = /unicode-range:\s*([^;]+);/.exec(fs.readFileSync(css, 'utf8'));
  return m ? m[1].trim() : null;
}

let imports = '';
let entries = '';
let n = 0;
for (const [family, [pkg, listed]] of Object.entries(FAMILIES)) {
  const faces = [];
  // Every bundled weight also gets its italic where the family has one, so Italic never
  // falls back to another weight. Families without italics are slanted by the browser.
  const weights = [...new Set(listed.flatMap((w) => (w.endsWith('i') ? [w] : [w, `${w}i`])))];
  for (const w of weights) {
    const italic = w.endsWith('i');
    const weight = parseInt(w, 10);
    for (const subset of ['latin', 'latin-ext']) {
      const file = `${pkg}-${subset}-${weight}-${italic ? 'italic' : 'normal'}.woff2`;
      if (!fs.existsSync(path.join(root, pkg, 'files', file))) continue;
      const v = `f${n++}`;
      imports += `import ${v} from '@fontsource/${pkg}/files/${file}?url';\n`;
      const range = unicodeRange(pkg, subset);
      faces.push(`{ url: ${v}, weight: ${weight}, italic: ${italic}${range ? `, unicodeRange: ${JSON.stringify(range)}` : ''} }`);
    }
  }
  entries += `  { family: ${JSON.stringify(family)}, category: ${JSON.stringify(CATEGORY[family] ?? 'sans')}, faces: [\n    ${faces.join(',\n    ')},\n  ] },\n`;
}

const out = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
${imports}
export interface FontFaceEntry { url: string; weight: number; italic: boolean; unicodeRange?: string }
export interface FontFamilyEntry { family: string; category: 'sans' | 'serif' | 'script' | 'display' | 'mono'; faces: FontFaceEntry[] }

export const BUNDLED_FONTS: FontFamilyEntry[] = [
${entries}];
`;
fs.writeFileSync('src/engine/fontManifest.ts', out);
console.log('fonts:', Object.keys(FAMILIES).length, 'faces:', n);
